### ISSUE TITLE
Repo size is big (~1.2 GB), need to clean up

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#204] opened 2019-02-20 17:40 UTC
@xylar reported that the repo size is about 1.2 GB large, we may need a clean up.

**Comment by xylar** [comment] 2019-02-20 18:07
Here's a little bit of info on how to do that:
https://stackoverflow.com/questions/2116778/reduce-git-repository-size

**Comment by xylar** [comment] 2019-08-17 19:23
I'm working on #242 and noticed again how huge the repo is.  It takes a long time to build a python package for e3sm_diags because of this.  I just want to make sure it's still on the radar to be fixed sooner or later.

**Comment by chengzhuzhang** [comment] 2019-08-19 22:24
I tried the `stackoverflow` a while ago and didn't fix the size issue somehow. Yes, this issue is still on my radar. I will try again before our v2.0.0 release. Thanks for the reminder...

**Comment by tomvothecoder** [comment] 2021-03-12 18:07
Duplicate of #306

**Closed by tomvothecoder** 2021-03-12 18:07 UTC
