### ISSUE TITLE
ncclimo for monthly and seasonal means

### ISSUE THREAD

**Issue by lee1046** [E3SM-Project/e3sm_diags#543] opened 2021-11-23 17:40 UTC
https://github.com/E3SM-Project/e3sm_diags/blob/8852aefabd561c0ad27118be5aa91ab01f062321/model_data_preprocess/postprocessing_E3SM_data_for_e3sm_diags.sh#L55

I learned that --clm_md=mth is needed to generate monthly means and seasonal & annual means from h0 files. Without --clm_md=mth, you just get only monthly timeseries data.

**Comment by chengzhuzhang** [comment] 2021-11-23 18:04
Hey @lee1046, `mth` should be the default option of `--clm_md`. In current version of `ncclimo`, splitting mode (timeseries mode) only activate "when it receives a list of files through a pipe to stdin, or alternatively placed as positional arguments (after the last command-line option), or if neither of these is done and no caseid is specified. " In this line, i expect if `caseid` is specified, it still use climatology mode. I'm wondering if you see a different behavior when testing this script?

**Comment by chengzhuzhang** [comment] 2022-05-26 21:24
I tested the ncclimo call in the prostprocessing script should work.

**Comment by chengzhuzhang** [comment] 2022-05-27 16:03
I think the problem is actually in time-series splitting line: `cd ${drc_in};eval ls ${caseid}.${atm_name}.h0.*{${start}..${end}}*.nc | ncclimo -P ${atm_name} --caseid=${caseid} --var=U,CLDHGH,CLDLOW,CLDMED,CLDTOT,FLNS,FLUT,FSNS,FSNT,FSNTOA,LANDFRAC,LHFLX,LWCF,OCNFRAC,PRECC,PRECL,PSL,QFLX,SHFLX,SWCF,T,TAUX,TAUY,TREFHT,TS --yr_srt=$start --yr_end=$end --drc_out=${drc_out} -O $drc_rgr --map=${map_file}` This line now also generated climo files...

**Comment by chengzhuzhang** [comment] 2022-06-03 00:06
closed by #593

**Closed by chengzhuzhang** 2022-06-03 00:06 UTC
