### ISSUE TITLE
Likely problem with GPCP v2.3

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/e3sm_diags#213] opened 2019-04-15 15:11 UTC
I was comparing annual lat-lon figures for GPCP v2.2 and v2.3 from E3SM Diags v1.6.1. It appears very likely that there is a bug. Model data (top panels) are identical between the two plots as expected. Obs data (middle panels) show only minor differences, but Model - Obs (bottom panels) look very different for 2.2 and 2.3 (RMSE increasing from 1.1 to 1.4). Something doesn't look like to me.

Model vs GPCP 2.2:

![GPCP_v2 2-PRECT-ANN-global](https://user-images.githubusercontent.com/15743046/56143296-1e7edc00-5f55-11e9-9b00-50df9200f764.png)

Model vs GPCP 2.3:

![GPCP_v2 3-PRECT-ANN-global](https://user-images.githubusercontent.com/15743046/56143341-3a827d80-5f55-11e9-88eb-e60d14f0c478.png)

**Comment by zshaheen** [comment] 2019-04-15 18:37
@golaz, can you post your parameter file(s)? I want to see your `reference_data_path` parameter and any time slicing you're doing. Though like you're saying, this might not be a problem with the data. In v1.6.1, we did update to use the latest CDAT. I'll tests with older versions of e3sm_diags.

Tip: If you're running with a container on NERSC, you can view the versions of the container on the machine:
```
shifterimg images | grep e3sm_diags
```

From [our releases](https://github.com/E3SM-Project/e3sm_diags/releases), you can download a specific version:
```
shifterimg -v pull docker:e3sm/e3sm_diags:A_SPECIFIC_VERSION
```

And then run that specific version:
```
python e3sm_diags_container.py --shifter --container_version A_SPECIFIC_VERSION -p myparams.py
```

**Comment by golaz** [comment] 2019-04-15 21:11
The figures are from @xuezhengllnl, generated with your help.

**Comment by zshaheen** [comment] 2019-04-15 21:13
Hi @xuezhengllnl, if you can post the parameter files here, that would be great!

**Comment by xuezhengllnl** [comment] 2019-04-15 21:17
@zshaheen 

reference_data_path = '/global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/climatology/'
test_data_path = '/global/cscratch1/sd/xzheng/E3SM_model_data_for_diags/edison.20190325-master.EAMv1P_CTL2.ne30_ne30/rgr/'
test_name = 'edison.20190325-master.EAMv1P_CTL2.ne30_ne30'
#sets = ['lat_lon']
#seasons = ["ANN"]
# 'mpl' and 'vcs' are for matplotlib or vcs plots respectively.
backend = 'mpl'
# Name of folder where all results will be stored.
results_dir = '/global/project/projectdirs/acme/www/xzheng/E3SM_Diags/v1p_ctl/diag_demo'
multiprocessing = True
num_workers =  24

**Comment by zshaheen** [comment] 2019-04-15 21:34
@xuezhengllnl, can you give me read permission on the `test_data_path` directory?

**Comment by xuezhengllnl** [comment] 2019-04-15 21:36
> @xuezhengllnl, can you give me read permission on the `test_data_path` directory?

It should be accessible now...

**Comment by zshaheen** [comment] 2019-04-15 22:47
@xuezhengllnl Thanks, it is. As @golaz said, it seems like there's something wrong with how this data is being handled for GPCP v2.3. I've reran your results with v1.6.0 and it matched the output of v1.6.1, so updating our dependencies **did not** cause this issue.

* Since we're doing model vs obs for the latitude-longitude contour maps, I looked in the [default diags folder](https://github.com/E3SM-Project/e3sm_diags/tree/master/acme_diags/driver/default_diags) for `lat_lon_model_vs_obs.cfg`.
* In this, I extracted all of the runs we wanted into a file, `gcpc.cfg`:
```ini
[#]
sets = ["lat_lon"]
case_id = "GPCP_v2.2"
variables = ["PRECT"]
ref_name = "GPCP_v2.2"
reference_name = "GPCP"
seasons = ["ANN", "DJF", "MAM", "JJA", "SON"]
regions = ["global"]
test_colormap = "WhiteBlueGreenYellowRed.rgb"
reference_colormap = "WhiteBlueGreenYellowRed.rgb"
diff_colormap = "BrBG"
contour_levels = [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
diff_levels = [-5, -4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4, 5]


[#]
sets = ["lat_lon"]
case_id = "GPCP_v2.3"
variables = ["PRECT"]
ref_name = "GPCP_v2.3"
reference_name = "GPCP"
seasons = ["ANN", "DJF", "MAM", "JJA", "SON"]
regions = ["global"]
test_colormap = "WhiteBlueGreenYellowRed.rgb"
reference_colormap = "WhiteBlueGreenYellowRed.rgb"
diff_colormap = "BrBG"
contour_levels = [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
diff_levels = [-5, -4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4, 5]
```

Then with your Python parameters file, I ran it like so. It seems like we can now run containers on the login node, so there's even less wait.

```
python e3sm_diags_container.py --container_version v1.6.0 --shifter -p params.py -d gpcp.cfg
```

Below are the results:

**Model vs GPCP v2.2:**
![2 2_v1 6 0](https://user-images.githubusercontent.com/4239938/56170182-70475680-5f95-11e9-9940-40616318155a.png)

**Model vs GPCP v2.3:**
![2 3_v 1 6 0](https://user-images.githubusercontent.com/4239938/56170202-7f2e0900-5f95-11e9-9016-4eee57c75411.png)

---

I'll see if I can somehow figure out what's wrong.

**Comment by chengzhuzhang** [comment] 2019-04-16 03:45
@zshaheen Thanks for helping out! I took a look at the difference between GPCP2.2 and 2.3 (https://www.ncbi.nlm.nih.gov/pubmed/30013797) Looking at the climatology averaged over (1979 and 2013) the difference between two data version shouldn't be as large as what we see here using e3sm_diags. I agree with @golaz there should be data problem. 

The scripts to processing GPCP 2.3 are the same as that for GPCP 2.2 https://github.com/E3SM-Project/e3sm_diags/blob/master/analysis_data_preprocess/process_GPCP_dataset.py and https://github.com/E3SM-Project/e3sm_diags/blob/master/analysis_data_preprocess/process_GPCP_dataset.py, but I used a newer version of CDAT, than what Chris Terai used when processing 2.2. I will take a futher look when I get back next week...

**Comment by golaz** [comment] 2019-04-16 14:56
I wonder whether something goes wrong when the fields are remapped to a common grid in order to make the difference panel plot. Are the grids identical for GPCP v2.2 and v2.3?

**Comment by zshaheen** [comment] 2019-04-16 16:57
Regardless of the env that the data was created in, they all should be created in the same env. It makes since that GCPC 2.3 was created with different versions of software, it was added in after the other observational data.

For provenance reasons, the default e3sm_diags created from [the env yml files](https://github.com/E3SM-Project/e3sm_diags/tree/master/conda) should be used. So since GPCP was added in v1.6.0, a person can go to the code for the that version and use the env yml (if it still works) to process the data.

If we do find that the different envs are causing this issue, then doing the above with all the obs data would be a good idea.

**Comment by beharrop** [comment] 2019-04-16 18:58
For what it's worth, I have seen this same sort of thing when I run e3sm_diags.  If you line the two figures up next to each other (or flip between them) it is obvious that the biases in v2.3 are shifted northward compared to v2.2.  I suspect @golaz is right that there is a problem with the gridding of the two data products.

**Comment by chengzhuzhang** [comment] 2019-05-07 21:40
This is confirmed to be a data problem. I obtained original v2.2 data to make a comparison (thanks to @crterai). The v2.2 original data doesn't have latitude bounds and these need to be manually set in its post-processing script, while these are no longer correct for v2.3 data. After I removed lines to set lat-bounds, we v2.2 and v2.3 compares closely:
![GPCP_v2 3-PRECT-ANN-global_new](https://user-images.githubusercontent.com/13056557/57334766-8ac4a980-70d5-11e9-8ca5-1ee48a34898f.png)
Below is the old comparison:
![GPCP_v2 2-PRECT-ANN-global_wrong](https://user-images.githubusercontent.com/13056557/57334801-a92aa500-70d5-11e9-868a-8fd5f04d0dd6.png)

The code fix is in https://github.com/E3SM-Project/e3sm_diags/pull/214. It will be merged after review. The GPCP datasets on acme1 and nersc are updated.

**Comment by zshaheen** [comment] 2019-05-28 20:42
Fixed in 9df26c8686d647fe43ea1bbdf3f70efef4db9e58.

**Comment by golaz** [comment] 2021-03-03 17:10
@chengzhuzhang and @forsyth2 : I'm re-opening this old issue. It appears that the bad GPCPv2.3 is available somewhere on lcrc and @vanroekel has been inadvertently using it leading to unecessary confusion. We need to urgently delete any old data repository that is no longer maintained.

**Comment by vanroekel** [comment] 2021-03-03 17:30
@chengzhuzhang and @forsyth2 and @golaz it appears the problem is my plot config file was pointed at data here
```
/lcrc/group/acme/diagnostics/obs_for_e3sm_diags/climatology
```
but should have used
```
/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology
```
I will try my plots with the latter path and report back

**Comment by chengzhuzhang** [comment] 2021-03-03 17:42
Thank you @vanroekel . I'm deleting `/obs_for_e3sm_diags` and `/obs_for_acme_diags`  under `/lcrc/group/acme/diagnostics/` to avoid future confusion.

**Comment by vanroekel** [comment] 2021-03-04 14:20
@chengzhuzhang Just to confirm the plots look correct with this change in path, but may I ask why e3sm-diags has chosen to have diagnostics in a different spot from mpas-analysis?  It seems like this could lead to continued confusion and issues for people like me.

**Comment by chengzhuzhang** [comment] 2021-03-10 06:55
@vanroekel Hi, thanks for confirming. I had a short conversation with Xylar on slack. The analysis data are not coordinated well as we would expect. Especially e3sm-diags was created later, and I was not aware of the coordination until separate paths of observation data for e3sm-diags were established on different machines. I will work with @xylar to try to find a good solution.  But it's gonna be a different issue. I'm closing this one.

**Closed by chengzhuzhang** 2021-03-10 06:55 UTC
Labels: bug
